package com._xibrahim.cards.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(name = "CardResponse", description = "Card response returned by the cards API.")
public class CardResponseDto {

    @Schema(description = "Primary key generated by the database.", example = "1")
    private Integer cardId;

    @Schema(description = "Customer mobile number linked to the card.", example = "01012345678")
    private String mobileNumber;

    @Schema(description = "Unique card number generated by the service.", example = "5123456789012345")
    private String cardNumber;

    @Schema(description = "Card type.", example = "Credit")
    private String cardType;

    @Schema(description = "Total spending limit assigned to the card.", example = "100000")
    private Integer totalLimit;

    @Schema(description = "Amount already used from the card limit.", example = "25000")
    private Integer amountUsed;

    @Schema(description = "Remaining amount available on the card.", example = "75000")
    private Integer availableAmount;
}
