package com._xibrahim.accounts.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(name = "AccountResponse", description = "Account response enriched with the owning customer's name.")
public class AccountResponseDto {
    @Schema(description = "Unique account number generated by the service.", example = "1234567890")
    private Long number;

    @Schema(description = "Account type.", example = "Savings")
    private String type;

    @Schema(description = "Branch address attached to the account.", example = "123 Main Street, New York")
    private String branchAddress;

    @Schema(description = "Name of the customer who owns the account.", example = "Ibrahim Elsayed")
    private String customerName;
}
