package com._xibrahim.loans.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(name = "LoanResponse", description = "Loan response returned by the loans API.")
public class LoanResponseDto {

    @Schema(description = "Primary key generated by the database.", example = "1")
    private Integer loanId;

    @Schema(description = "Customer mobile number linked to the loan.", example = "01012345678")
    private String mobileNumber;

    @Schema(description = "Unique loan number generated by the service.", example = "900123456789")
    private String loanNumber;

    @Schema(description = "Loan type.", example = "Home")
    private String loanType;

    @Schema(description = "Total loan amount granted to the customer.", example = "500000")
    private Integer totalLoan;

    @Schema(description = "Amount already paid against the loan.", example = "125000")
    private Integer amountPaid;

    @Schema(description = "Remaining outstanding amount.", example = "375000")
    private Integer outstandingAmount;
}
